import { helpItem as IntroHelp } from './IntroHelp'
import { helpItem as QuickStartHelp } from './QuickStartHelp'
import { helpItem as EntryManageHelp } from './EntryManageHelp'
import { helpItem as TemplateHelp } from './TemplateHelp'
import { helpItem as SecurityHelp } from './SecurityHelp'
import { helpItem as PasswordSecurityHelp } from './PasswordSecurityHelp'
import { helpItem as DatabaseManageHelp } from './DatabaseManageHelp'
import { helpItem as AdvancedFeatureHelp } from './AdvancedFeatureHelp'
import { helpItem as BackupRestoreHelp } from './BackupRestoreHelp'
import { helpItem as TroubleshootingHelp } from './TroubleshootingHelp'
import { helpItem as VersionUpdateHelp } from './VersionUpdateHelp'
import { helpItem as DeveloperFeatureHelp } from './DeveloperFeatureHelp'
import { helpItem as FAQHelp } from './FAQHelp'

export const helpItems = [
  IntroHelp,
  QuickStartHelp,
  EntryManageHelp,
  TemplateHelp,
  SecurityHelp,
  PasswordSecurityHelp,
  DatabaseManageHelp,
  AdvancedFeatureHelp,
  BackupRestoreHelp,
  TroubleshootingHelp,
  VersionUpdateHelp,
  DeveloperFeatureHelp,
  FAQHelp
] 